packages:
  - chrome-extension
  - landing-page
  - pages/*
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
